apiVersion: v1
kind: Service
metadata:
  labels:
    app: website
  name: frontend
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
  selector:
    app: website
  type: LoadBalancer
  loadBalancerIP: 104.155.133.91
