kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  gcePersistentDisk:
    pdName: "mysql-vol"
    fsType: "ext4"
